/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  wikiSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '项目总览',
    },
    {
      type: 'category',
      label: '快速入门',
      collapsed: false,
      items: ['guide/getting-started'],
    },
    {
      type: 'category',
      label: '核心工作流',
      collapsed: false,
      items: [
        'workflow/providers',
        'workflow/voice-bank',
        'workflow/quick-tts',
        'workflow/dialog-tts',
        'workflow/phase-tts',
        'workflow/novel-reader',
        'workflow/video-dub',
      ],
    },
    {
      type: 'category',
      label: '配置与运维',
      collapsed: false,
      items: [
        'operations/settings-tasks-storage',
        'operations/api-server',
        'operations/storage-troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'API 参考',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'api-zh',
          label: '中文 API',
        },
        {
          type: 'doc',
          id: 'api',
          label: 'English API',
        },
      ],
    },
    {
      type: 'category',
      label: '项目状态',
      collapsed: true,
      items: [
        'project-docs',
        'plan',
        'bugs',
      ],
    },
    {
      type: 'category',
      label: '研究资料',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: '研究资料',
        slug: '/category/research',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'research',
        },
      ],
    },
    {
      type: 'category',
      label: '历史归档',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: '历史归档',
        slug: '/category/archive',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'archive',
        },
      ],
    },
  ],
};

module.exports = sidebars;
